spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tech-inventory
    username: postgres
    password:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      location: uploads